{{ if .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epinio
  namespace: epinio
spec:
  dnsNames:
  - epinio.{{ .Values.domain }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.server.tlsIssuer }}
  secretName: epinio-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epinio-ca
  namespace: {{ .Values.certManagerNamespace }}
spec:
  commonName: epinio-ca
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: epinio-ca-root

{{- end }}
