apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: "admin"
  name: admin-epinio-user
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.api.username }}
  password: {{ .Values.api.passwordBcrypt }}
---
apiVersion: v1
kind: Secret
type: BasicAuth
metadata:
  labels:
    epinio.io/api-user-credentials: "true"
    epinio.io/role: "user"
  name: default-epinio-user
  namespace: {{ .Release.Namespace }}
stringData:
  username: epinio
  # bcrypt hash for 'password'
  password: "$2a$10$6bCi5NMstMK781In7JGiL.B44pgoplUb330FQvm6mVXMppbXBPiXS"
  namespaces: |
    workspace
