# Default values for epinio-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# This is the API between the epinio server's deployment code, and
# charts implementing the deployment, like this one.

image:
  pullPolicy: IfNotPresent

imagePullSecrets: []

epinio:
  # appName: .Release.Name
  # namespace: .Release.Namespace
  replicaCount: 1
  appUID: 999
  stageID: 999
  imageURL: curl
  username: user
  routes: []
  env: {}
  services: []

# routes:   sequence of host names
# services: sequence of service names
# env:      mapping name/value

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
