# Copied from here:
# https://github.com/k3s-io/helm-controller/blob/341b2eaa41e5cb9247c119bfa34a7ad131c7ac51/manifests/crd.yaml
# NOTE: These files should be removed when integrated in Rancher marketplace
# because in Rancher, the CRDs become a separate helm chart and are always removed.
# When that happens with these CRDs here, any custom helmchart resource will be
# removed when Epinio is uninstalled, including Traefik and anything else Rancher
# deploys using the same mechanism.
# Since the Helmchart CRDs are already there in Rancher, we don't need to install
# them.
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmcharts.helm.cattle.io
spec:
  group: helm.cattle.io
  version: v1
  additionalPrinterColumns:
  - name: Job
    type: string
    description: Job associated with updates to this chart
    JSONPath: .status.jobName
  - name: Chart
    type: string
    description: Helm Chart name
    JSONPath: .spec.chart
  - name: TargetNamespace
    type: string
    description: Helm Chart target namespace
    JSONPath: .spec.targetNamespace
  - name: Version
    type: string
    description: Helm Chart version
    JSONPath: .spec.version
  - name: Repo
    type: string
    description: Helm Chart repository URL
    JSONPath: .spec.repo
  - name: HelmVersion
    type: string
    description: Helm version used to manage the selected chart
    JSONPath: .spec.helmVersion
  - name: Bootstrap
    type: boolean
    description: True if this is chart is needed to bootstrap the cluster
    JSONPath: .spec.bootstrap
  names:
    kind: HelmChart
    plural: helmcharts
    singular: helmchart
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmchartconfigs.helm.cattle.io
spec:
  group: helm.cattle.io
  version: v1
  names:
    kind: HelmChartConfig
    plural: helmchartconfigs
    singular: helmchartconfig
  scope: Namespaced
