---
name: "Autodiscovery - Application stateful"

autodiscovery:
  groupby: all
  scmid: default
  actionid: default
  crawlers:
    helm:
      versionfilter:
        kind: semver
      only:
        - path: "chart/application-stateful/*"

scms:
  default:
    kind: "github"
    spec:
      user: "{{ .github.epinio.user }}"
      email: "{{ .github.epinio.email }}"
      owner: "{{ .github.epinio.owner }}"
      repository: "{{ .github.epinio.repository }}"
      token: '{{ requiredEnv .github.epinio.token }}'
      username: "{{ .github.epinio.username }}"
      branch: "{{ .github.epinio.branch }}"

actions:
  default:
    kind: "github/pullrequest"
    scmid: "default"
    spec:
      title: Bump Application chart dependencies
      labels:
        - "dependencies"
        - "helm"
