apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "epinio-truncate" (print "i-" $.Values.epinio.appName) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "epinio-application.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.epinio.appName }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    - ports:
        - protocol: TCP
          port: 8080
