{{ if not .Values.manifestSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: manifest
stringData:
  manifest.yaml: |
    {{- $sessionKey := randAlphaNum 24 -}}
    {{- $password := randAlphaNum 12 }}
    ---
    components:
      {{- if not .Values.skipLinkerd }}
      - id: linkerd
        type: yaml
        source:
          path: assets/installer/linkerd-job.yaml
        waitComplete:
          - type: "job"
            selector: "linkerd-install"
            namespace: linkerd
      {{ end }}

      {{- if not .Values.skipTraefik }}
      - id: traefik
        {{- if not .Values.skipLinkerd }}
        needs: linkerd
        {{- end }}
        namespace: traefik
        type: helm
        source:
          name: traefik
          url: {{ .Values.traefikChart | quote }}
        waitComplete:
          - type: "pod"
            selector: "app.kubernetes.io/name=traefik"
          - type: "loadbalancer"
            selector: "traefik"
        values:
          - name: globalArguments
            value: ""
          - name: "deployment.podAnnotations.linkerd\\.io/inject"
            value: "enabled"
          - name: "ports.web.redirectTo"
            value: "websecure"
          - name: "ingressClass.enabled"
            value: "true"
          - name: "ingressClass.isDefaultClass"
            value: "true"
          - name: "service.spec.loadBalancerIP"
            value: "{{ .Values.loadbalancerIP }}"
      {{ end }}

      {{- if not (or .Values.skipCertManager .Values.useCustomTlsIssuer) }}
      - id: cert-manager
        namespace: cert-manager
        type: helm
        source:
          name: cert-manager
          path: assets/installer/cert-manager-v1.5.4.tgz
        values:
          - name: "installCRDs"
            value: "true"
          - name: "extraArgs[0]"
            value: "--enable-certificate-owner-ref=true"
        waitComplete:
          - type: "pod"
            selector: "app.kubernetes.io/name=webhook"
            namespace: "cert-manager"
          - type: "pod"
            selector: "app.kubernetes.io/name=cainjector"
            namespace: "cert-manager"
          - type: "pod"
            selector: "app.kubernetes.io/name=cert-manager"
            namespace: "cert-manager"
      {{ end }}

      - id: namespace-epinio
        {{- if not .Values.skipLinkerd }}
        needs: linkerd
        {{- end }}
        type: namespace
        namespace: epinio
        values:
          - name: linkerd.io/inject
            value: enabled
            type: annotation

      - id: epinio
        needs: namespace-epinio
        namespace: epinio
        type: helm
        source:
          name: epinio
          path: "{{ .Values.epinioChart }}"
        values:
          - name: email
            value: "{{ .Values.email }}"
          - name: "global.domain"
            value: "{{ .Values.domain }}"
          - name: "api.username"
            value: {{ default "admin" .Values.user | quote }}
          - name: "api.password"
            value: {{ default $password .Values.password | quote }}
          - name:  "certManagerNamespace"
            value: cert-manager
          - name: "server.sessionKey"
            value: "{{ $sessionKey }}"
          - name: "server.accessControlAllowOrigin"
            value: {{ default "*" .Values.accessControlAllowOrigin | quote }}
          - name: "global.tlsIssuer"
            value: {{ default .Values.tlsIssuer .Values.customTlsIssuer | quote }}
          - name: "server.timeoutMultiplier"
            value: {{ .Values.server.timeoutMultiplier }}
          - name: "server.traceLevel"
            value: "{{ .Values.server.traceLevel }}"
          {{ if .Values.ingress.ingressClassName }}
          - name: "server.ingressClassName"
            value: "{{ .Values.ingress.ingressClassName }}"
          - name: "ingress.ingressClassName"
            value: "{{ .Values.ingress.ingressClassName }}"
          {{ end }}

          - name: "minio.enabled"
            value: {{ .Values.minio.enabled }}
          - name: "s3.endpoint"
            value: {{ .Values.s3Endpoint | quote }}
          - name: "s3.bucket"
            value: {{ .Values.s3Bucket | quote }}
          - name: "s3.accessKeyID"
            value: {{ .Values.s3AccessKeyId | quote }}
          - name: "s3.secretAccessKey"
            value: {{ .Values.s3SecretAccessKey | quote }}
          - name: "s3.region"
            value: {{ .Values.s3Location | quote }}
          - name: "s3.useSSL"
            value: {{ .Values.s3UseSSL }}

          - name: "containerregistry.enabled"
            value: {{ .Values.containerregistry.enabled }}
          {{- if not .Values.containerregistry.enabled }}
          - name: "global.registryUrl"
            value: {{ .Values.externalRegistryURL | quote }}
          - name: "global.registryUsername"
            value: "{{ .Values.externalRegistryUsername }}"
          - name: "global.registryPassword"
            value: "{{ .Values.externalRegistryPassword }}"
          - name: "global.registryNamespace"
            value: "{{ .Values.externalRegistryNamespace }}"
          {{- end }}
        preDeploy:
          - type: "pod"
            selector: "app.kubernetes.io/name=webhook"
            namespace: "cert-manager"
{{ end }}
