{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epinio-registry
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - "epinio-registry.{{ .Values.global.domain }}"
  issuerRef:
    kind: ClusterIssuer
    name: {{ default .Values.global.tlsIssuer .Values.global.customTlsIssuer | quote }}
  secretName: epinio-registry-tls
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "kubed-registry-tls-from={{ .Release.Namespace }}" # Sync certificate to matching namespaces
{{- end }}
